FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./ ./

USER root

RUN apk add --no-cache \
	libc6-compat \
	make

RUN npm install -g truffle
RUN npm install