version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    container_name: blockchain
    command: "--accounts 50 --d --e 1000 -l 80000000"
  smart-contract-deploy:
    image: ismail-30/trufflesuite:latest
    command: "truffle test"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app/
    depends_on:
      - "ganache"